snapsecret-data:
  image: busybox
  volumes:
    - /data/db
snapsecret-mongo:
  image: 'tutum/mongodb:latest'
  environment:
    MONGODB_PASS: foobar
  volumes_from:
    - snapsecret-data
snapsecret-web:
  build: ./
  environment:
    PORT: 3000
  links:
    - snapsecret-mongo
  ports:
    - 3000
